### ISSUE TITLE
Swift 2 compatibility

### ISSUE THREAD

**Issue by wimhaanstra** [alex-alex/S2Geometry#2]
I love that there is a S2 Geometry library finally available in Swift, because I would like to get this working in a Swift project. The current sources are made for Swift 3, but the release window for this is still quite uncertain (late 2016).

I have been trying to convert it to Swift 2, but I keep hitting certain limitations (most of the simply resolved by removing parameter names in function calls, . Would it be possible to create a Swift 2 version of this library. The thing I keep ending up with, is that `IteratorProtocol` is unsupported in Swift 2.

Or is it possible to build this to a Framework and include this in a compiled form in my Swift 2 project?

**Comment by alex-alex** [comment]
The reason for Swift 3 is because this project is in early stage and still work in progress, I wouldn't recommend using it in production software yet.

`IteratorProtocol` has been renamed from `GeneratorType` in Swift 2.

**Comment by romsi** [comment]
@depl0y check out my pull request #4. If you really need the swift 2.0 compatibility, I hope this will help you.
